Body = "Test this"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "My New Hugo Site"
baseURL = "/"

[Params]
logo = "/images/core-cognition-logo.svg"
alt = "asds"
url = "/"
favicon = ""
blogpostId = "619f99a4cb879275fad566e6"
siteId = "61996b3541cc105c084a9af1"

[taxonomies]
Tag = "tags"
Category = "categories"
Author = "authors"

[Language]

[languages]

[languages.en]
contentDir = "content/English"
languageName = "EN"
weight = 20
languagedirection = "rtl"

[languages.en.menu]

[[languages.en.menu.navmenu]]
name = "BASICS"
url = "/basics"
weight = 1

[[languages.en.menu.navmenu]]
name = "Analyses"
url = "/analyses"
weight = 2

[[languages.en.menu.navmenu]]
name = "Blog"
url = "/blog"
weight = 3

[[languages.en.menu.navmenu]]
name = "About"
url = "/about"
weight = 4

[languages.nl]
contentDir = "content/Dutch"
languageName = "NL"
weight = 5

[languages.fr]
contentDir = "content/French"
languageName = "FR"
weight = 5

[languages.fr.menu]

[[languages.fr.menu.navmenu]]
name = "BASIC INSIGHT"
url = "/basic-insight"
weight = 1